/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface VehicleRecord {
  'id' : bigint,
  'challanNumber' : string,
  'action' : string,
  'supplier' : string,
  'date' : string,
  'vehicleNumber' : string,
  'time' : string,
  'units' : bigint,
  'driverName' : string,
}
export interface _SERVICE {
  'addRecord' : ActorMethod<
    [string, string, string, string, string, bigint, string, string],
    bigint
  >,
  'deleteRecord' : ActorMethod<[bigint], undefined>,
  'getAllRecords' : ActorMethod<[], Array<VehicleRecord>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];