/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleRecord = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'supplier' : IDL.Text,
  'date' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'time' : IDL.Text,
  'units' : IDL.Nat,
  'driverName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(VehicleRecord)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleRecord = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'supplier' : IDL.Text,
    'date' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'time' : IDL.Text,
    'units' : IDL.Nat,
    'driverName' : IDL.Text,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(VehicleRecord)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };